version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports: 
      - "80:80"
      - "443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./www/certs:/etc/nginx/certs:ro
      - ./www/htpasswd:/etc/nginx/htpasswd
      - proxy-data:/etc/nginx/vhost.d
      - proxy-data:/usr/share/nginx/html
      - ./my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf
    restart: always
    networks: 
      - ssl_proxy
  letsencrypt:  
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - ./www/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-data:/etc/nginx/vhost.d
      - proxy-data:/usr/share/nginx/html
    restart: always
    networks: 
      - ssl_proxy
networks:
  ssl_proxy:
    external: true
volumes:
  proxy-data:
    external: true